### ISSUE TITLE
about braces and indentation wars

### ISSUE THREAD

**Issue by pikeview** [thewhitetulip/web-dev-golang-anti-textbook#15]
Hi,
The write up about Go curly brackets syntax and indentation wars might need changes in 
https://github.com/thewhitetulip/web-dev-golang-anti-textbook/blob/master/content/02.1.md

The fact that go cannot have opening curly bracket at the beginning of the line is an "unintended consequence" of doing away with semicolons

see Rob Pike's talk about braces here https://youtu.be/VoS7DsT1rdM?t=1353

**Comment by thewhitetulip** [comment]
The point I wished to make in the chapter which you referred was that Go has a standard way of writing code. Unlike PEP8, which was added a lot after the language was invented, Go was designed bottom up on the rigid guidelines.

I had no idea if the semi-colon vs braces war was averted due to an intended consequence or an unintended consequence, and I hope I am not stating a factually incorrect statement in the chapter!

I can add the contents of your issue to the chapter though, either that or I need to change the wording to not imply that they designed the language to not have the braces vs indentation wars. But in many blog posts I read about Go from the authors, I wish I had kept the links handy, they had mentioned that Go was built so that programmers write large scale distributed software in large teams effectively, and it surely helped that the language spec are small enough to fit entirely in our head, plus the standardized `gofmt` is of great help and that happens _because_ of the strict guidelines!

**Comment by pikeview** [comment]
Hi Suraj,
  I was not referring to braces vs tabs/spaces.
  I was referring to the two formatting styles based on the location of the opening curly brace

  Quote "..or I need to change the wording to not imply that they designed the language to not have the braces vs indentation wars" (or location of opening brace wars)

   yes, something along those lines might be a good idea..

**Comment by thewhitetulip** [comment]
Hi Manas,
The thing is the formatting styles example is there only to state that there are formatting styles in other languages like C, Java etc But when it comes to Go, we don't have them.
I really need to make it less complicated!

Thanks!

**Comment by thewhitetulip** [comment]
@pikeview 

I have modified the chapter(all chapters). I hope the ambiguity is clear now!

If not, do comment here, I'll modify it again.
