### ISSUE TITLE
What is the license for this book? 

### ISSUE THREAD

**Issue by WildYorkies** [thewhitetulip/web-dev-golang-anti-textbook#40]
Can I translate it to a different programming language, for example?

**Comment by tedyoung** [comment]
License: https://github.com/thewhitetulip/web-dev-golang-anti-textbook#license

Seems to me if it's a different programming language, then it's going to be quite a different book?

**Comment by thewhitetulip** [comment]
Do you want to translate the book to another language? Or use the methodology of this book?

You are welcome to do both :-) of you want to write another book go ahead, if you want to contribute translatipn for this book, I'll have to take a look at how leanpub handles translations.

**Comment by WildYorkies** [comment]
@thewhitetulip Translate it to a different programming language, not natural language :)

I'm thinking of translating it to perl6 actually. Since that language also has channels, etc. Mostly it would help me learn perl6 in the process. I like your methodology of this book because it's very primitive and doesn't rely extensively on external dependencies.

**Comment by thewhitetulip** [comment]
@WildYorkies Feel free to translate it. But I do not think that would come under translate, usually translation means from English to Spanish, as @tedyoung said, if you write an "antitextbook" for perl it'd be another book altogther. After you write the book do give me the link, I'll learn perl6 and try to contribute :-)

Technically speaking you don't have to attribute anything back to this project because you are _not_ taking the text, you are taking ideas, but if you want, you can link this in the readme and say that this inspired you.

It is perfectly fine/legal if you don't attribute.

**Comment by thewhitetulip** [comment]
@WildYorkies When you write the book, I'd like to add it in https://github.com/thewhitetulip/multiversity (You can make a YouTube series too)
